name: GoBuster
# Controls when the action will run. Workflow runs when manually triggered using the UI or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      domain:
        description: 'Domain To Scan'
        default: 'https://example.com/path/to/folder'
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  GoBuster:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Set up environment
    - name: Docker Pull
      run: docker pull ghcr.io/oj/gobuster:latest

      #GoBuster Dir
    - uses: actions/checkout@v4
    - name: Docker Run
      working-directory: ./
      run: docker run --rm -v ${{ github.workspace }}/GoBuster-DirWordList.txt:/GoBuster-DirWordList.txt ghcr.io/oj/gobuster dir -u ${{ github.event.inputs.domain }} -w /GoBuster-DirWordList.txt --exclude-length 0
      
